name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpasqsqwdqwd
  - wqd
  - pip:
    - ipydatagrid
    - bqplot
